# Generated by Django 4.2.3 on 2023-08-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=75)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PetShower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("petname", models.CharField(max_length=50)),
                ("ownername", models.CharField(default="", max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("bookingdate", models.DateTimeField()),
                ("petsize", models.CharField(max_length=1)),
                ("observations", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PetToy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toyname", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
