# Generated by Django 4.2.3 on 2023-08-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0002_alter_petshower_bookingdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petshower",
            name="bookingdate",
            field=models.DateTimeField(),
        ),
    ]
